### ISSUE TITLE
Wrong line length in HEX mode

### ISSUE THREAD

**Issue by Nevada317** [Jeija/gtkterm#11] opened 2019-03-16 03:50 UTC
I've stumbled to the problem while using FT232R based cable. When remote side send somewhat large amount of data (ex. 8 bytes) instead of typical 1-2 bytes per iteration, terminal shows one extra byte in line.

I've tracked down this issue to
```
vte_terminal_get_cursor_position(VTE_TERMINAL(display), &column, &row);
```
function call. It returns same column and row twice. Here is the example of some debug prints:

```
Column: 47, row: 70
Adding: 32, bytes=15
Loop ended

Column: 0, row: 71
Adding: 38, bytes=0
Adding: 2D, bytes=1
Loop ended

Column: 0, row: 71
Adding: FF, bytes=0
Adding: 22, bytes=1
Adding: FF, bytes=2
Adding: 20, bytes=3
Adding: 20, bytes=4
Loop ended
```

Looks like one of two possible issues is happening:
1) VTE does not react to feeding as fast as needed,
or
2) there is a race condition due to next data arrival.

Here is what I got:
![2019-03-16-032532_1144x481_scrot](https://user-images.githubusercontent.com/38298762/54470381-b4d5ab80-47b7-11e9-8bd6-2209f8930718.png)

**Comment by wvdakker** [comment] 2019-05-09 08:36
Hi,

Sorry for the late response. 
I have tried to pin it down, however I cannot reproduce it.
Is it with a certain data-stream? Or with all streams?

/Willem

**Comment by phako** [comment] 2019-08-08 07:55
I can easily reproduce it with the script below, then connecting to the pts it prints

```python
#!/usr/bin/env python3

import os
import time


(master, non_master) = os.openpty()

print('Providing our service at {0}'.format(os.ttyname(non_master)))

with open(master, "wb+", buffering=0) as term:
    while True:
        time.sleep(0.01)
        term.write(bytes([1,2,3,4,65]))
```

**Comment by wvdakker** [comment] 2019-11-07 20:32
I have rewritten the put_hexadecimal function. The vte_terminal_get_cursor_position did not return always the actual column as phako already concluded.
For now I used a virt_col_pos pointer which holds the actual bytes pos.

I have tested it and it works also with the index. Please let me know if there are any issues.

After this I guess we can make a new release and make it available in the Debian/Ubuntu distro.
I dont know if there are other branches which have to be merged.

/Willem

**Closed** 2019-12-18 08:07 UTC
